title = "Reilly Tucker Siemens"
description = "The canonical web presence of Reilly Tucker Siemens."
base_url = "https://tuckersiemens.com"
generate_categories_pages = false
generate_tags_pages = false
generate_feed = true
feed_filename = "rss.xml"
compile_sass = true

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"

[link_checker]
skip_prefixes = [
    "https://192.168.1.1",
    "https://router.asus.com",
]
skip_anchor_prefixes = [
    "https://github.com/",
]

[extra]
author = "Reilly Tucker Siemens"
