title = "Reilly Tucker Siemens"
description = "Tucker's website."
base_url = "https://tuckersiemens.com"
minify_html = true
compile_sass = true
generate_feeds = true
feed_filenames = ["rss.xml"]
taxonomies = [
  { name = "tags", feed = false },
]

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"

[link_checker]
skip_prefixes = [
    "https://192.168.1.1",
    "https://router.asus.com",
]
skip_anchor_prefixes = [
    "https://github.com/",
]

[extra]
author = "Reilly Tucker Siemens"
